name: pro007
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_icons:
  cupertino_icons: ^1.0.0
    # bottom navigation bar
  bottom_navy_bar: ^5.5.0
  story_view: ^0.12.3

  # adding maps 
  google_maps_place_picker: ^0.9.4
  flutter_google_places: ^0.2.3
  google_maps_webservice: ^0.0.14
  google_maps_flutter: ^0.5.30
  google_fonts: ^1.1.0
  # swipe
  swipe_button: ^0.0.2
  date_picker_timeline: ^1.2.1
  # image picker 
  image_picker: ^0.6.7+1
  sms_autofill: ^1.2.5
  get: ^3.12.1
  uuid: ^2.2.2
  email_validator: ^1.0.5
  shared_preferences: ^0.5.12
  sqflite: ^1.3.1+2
  toast: ^0.1.5

  # dotted-border
  dotted_border: ^1.0.5




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
      - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Gilroy
      fonts:
          - asset: assets/fonts/Gilroy-Light.otf
          - asset: assets/fonts/Gilroy-ExtraBold.otf
